version: "3.3"
services:
  db:
    image: mysql:8
    container_name: zemikadai2
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
